import "./globals.css";
import Navabar from "./compoments/Navbar";
import Footer from "./compoments/Footer";

import { ThemeProvider } from 'next-themes'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="dark" suppressHydrationWarning lang="en">

      <body>

      <ThemeProvider>
      <Navabar />

      <main>
        {children}

        </main>

      
      <Footer />

      </ThemeProvider>
        
        
      </body>
    </html>
  );
}
