import "./globals.css";
import Navabar from "./components/Navbar";
import Footer from "./components/Footer";
import Providers from './components/ProgressBarProvider';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  suppressHydrationWarning lang="en">

      <body>

      <Navabar />

      <main>
      <Providers>{children}</Providers>

        </main>

      
      <Footer />

        
        
      </body>
    </html>
  );
}
